function spectrum = total_spectrum(a,omega,eps)
spectrum = spherical_cs(1,1,a,omega,eps)...
    + spherical_cs(1,2,a,omega,eps)...
    + spherical_cs(1,3,a,omega,eps)...
    + spherical_cs(2,1,a,omega,eps)...
    + spherical_cs(2,2,a,omega,eps)...
    + spherical_cs(2,3,a,omega,eps);